version: '2.4'
services:

  database:
    image: sameersbn/postgresql:15-20230628
    container_name: backend-api-db
    environment:
      - DB_NAME=backend-api-db,backend-api-db-test
      - PG_TRUST_LOCALNET=true
      - PG_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - ./.db/initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  api:
    build:
      context: .
      target: dev
    image: backend-api-koa:dev
    container_name: backend-api-koa
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@database:5432/backend-api-db"
      PORT: 3000
    depends_on:
      database:
        condition: service_healthy
